export enum ErrorCodes {
  MANGA_NOT_FOUND = 'MANGA_NOT_FOUND',
  MANGA_ALREADY_EXISTS = 'MANGA_ALREADY_EXISTS',
  CHAPTER_ALREADY_EXISTS = 'CHAPTER_ALREADY_EXISTS',
  CHAPTER_NOT_FOUND = 'CHAPTER_NOT_FOUND',
  CHAPTER_DOES_NOT_BELONG_TO_MANGA = 'CHAPTER_DOES_NOT_BELONG_TO_MANGA',
}
