export enum ErrorCodes {
  CRON_JOB_NOT_FOUND = 'CRON_JOB_NOT_FOUND',
  CRON_JOB_ALREADY_EXISTS = 'CRON_JOB_ALREADY_EXISTS',
  CRON_JOB_INVALID_SCHEDULE = 'CRON_JOB_INVALID_SCHEDULE',
  CRON_JOB_DEACTIVATED = 'CRON_JOB_DEACTIVATED',
  CRON_JOB_EXECUTION_NOT_FOUND = 'CRON_JOB_EXECUTION_NOT_FOUND',
  CRON_JOB_EXECUTION_NOT_RUNNING = 'CRON_JOB_EXECUTION_NOT_RUNNING',
}
