export const MANGA_REPOSITORY = 'MangaRepository'
export const CHAPTER_REPOSITORY = 'ChapterRepository'
export const GENRE_REPOSITORY = 'GenreRepository'
export const DEMOGRAPHIC_REPOSITORY = 'DemographicRepository'
export const AUTHOR_REPOSITORY = 'AuthorRepository'
export const UPLOAD_REPOSITORY = 'UploadRepository'
